// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

long result = 0;
long a = 1;
long b = 2;
long tempsum = 0;



for(int i = 0; i <= 4000000; i++)
{
    if(b % 2 == 0)
    {
        result += b;
    }
    tempsum = a + b;
    a = b;
    b = tempsum;
}
Console.WriteLine($"Your result is {result} for sum of even number");